# Required project identifiers
sonar.projectKey=procurelinc
sonar.projectName=ProcureLinc
sonar.projectVersion=1.0

# Source configuration
sonar.sources=.

# SonarQube server
sonar.host.url=http://localhost:9000

# Authentication token
sonar.login=sqp_da89e447c964b6e91e142777097e25fa2f17a1cc
