export interface DeviceDetailItem {
  name: string;
  value: string;
}

export interface DeviceDetail {
  detail: DeviceDetailItem[];
}

export interface CategoryPaylaodType {
  mid: string;
  secretKey: string;
  reqId?: string;
  // txnId: string;
  clientUserId: string
  deviceDetial: DeviceDetail;
  udf1: string
  udf2: string,
  udf3: string,
  udf4: string,
  udf5: string,
  udf6: string,
  udf7: string,
  udf8: string,
  udf9: string,
  udf10: string
}



export interface DeviceDetailItem {
  name: string;
  value: string;
}

export interface DeviceDetail {
  detail: DeviceDetailItem[];
}

export interface ServicePayloadType {
  mid: string;
  secretKey: string;
  reqId: string;

  deviceDetial: DeviceDetail;

  udf1: string;
  udf2: string;
  udf3: string;
  udf4: string;
  udf5: string;
  udf6: string;
  udf7: string;
  udf8: string;
  udf9: string;
  udf10: string;

  billerName?: string;
  category?: string;
  billerId?: string
  pageNo?: number;
  pageSize?: number;
}



export interface ProviderType {
  mid: string;
  secretKey: string;
  deviceDetial: {
    detail: DeviceDetail[];
  };
  udf1: string;
  udf2: string;
  udf3: string;
  udf4: string;
  udf5: string;
  udf6: string;
  udf7: string;
  udf8: string;
  udf9: string;
  udf10: string;
  billerId: string;
  billerName?: string; // optional if needed later
}


export interface DeviceDetailItem {
  name: string;
  value: string;
}

export interface DeviceDetail {
  detail: DeviceDetailItem[];
}

export interface DeviceBlockTag {
  name: string;
  value: string;
}

export interface CustomerParamsRequest {
  tags: any[]; // you can replace any[] with your exact param type
}

export interface RemitterIdentity {
  name: string;
  value: string;
}

export interface BillFetchPayload {
  mid: string;
  secretKey: string;
  reqId?: string;          // generated by uniqueIdGenerator
  // txnId?: string;      // optional if needed
  deviceDetial: DeviceDetail;
  billerId: string;
  billerName: string;
  billerCategory: string;

  clientReqId: string;
  macAdress: string;
  customerMobNo: string;
  remitterName: string;
  paymentChannel: string;

  deviceBlockTags: DeviceBlockTag[];

  customerParamsRequest: CustomerParamsRequest;

  remitterIdentity: RemitterIdentity[];
}

export interface PlansPayload {
  mid: string;
  secretKey: string;
  reqId: string;
  deviceDetial: DeviceDetail; // Note: deviceDetial name retained as per JSON
  udf1: string;
  udf2: string;
  udf3: string;
  udf4: string;
  udf5: string;
  udf6: string;
  udf7: string;
  udf8: string;
  udf9: string;
  udf10: string;
  billerId: string;
  category: string;
  amountInRupees: string;
  circle: string;
  page: number;
  pagesize: number;
}


export interface BillValidationPayload {
  mid: string;
  secretKey: string;
  deviceDetial: DeviceDetail;
  udf1: string;
  udf2: string;
  udf3: string;
  udf4: string;
  udf5: string;
  udf6: string;
  udf7: string;
  udf8: string;
  udf9: string;
  udf10: string;
  billerId?: string | number;
  billerName?: string;
  billerCategory?: string;
  customerMobNo: string;
  macAddress: string;
  customerParamsRequest: CustomerParamsRequest;
}


export interface PaymentRequest {
  mid: string | number;
  secretKey: string;
  clientUserId: string;

  deviceDetial: {
    detail: {
      name: string;
      value: string;
    }[];
  };

  udf1?: string;
  udf2?: string;
  udf3?: string;
  udf4?: string;
  udf5?: string;
  udf6?: string;
  udf7?: string;
  udf8?: string;
  udf9?: string;
  udf10?: string;
  udf11?: string;
  udf12?: string;
  udf13?: string;
  udf14?: string;

  amount: number;
  currency: string;

  emailId?: string;
  customerVpa?: string;

  mobileNo: string;
  respUrl: string;

  txnReqType: 'PAY' | 'REFUND' | 'STATUS';

  name: string;
}

export interface PaymentPullbackType {
  mid: string | number;
  secretKey: string;
  clientUserId: string;
  deviceDetial: {
    detail: {
      name: string;
      value: string;
    }[];
  };

  udf1?: string;
  udf2?: string;
  udf3?: string;
  udf4?: string;
  udf5?: string;
  udf6?: string;
  udf7?: string;
  udf8?: string;
  udf9?: string;
  udf10?: string;
  udf11?: string;
  udf12?: string;
  udf13?: string;
  udf14?: string;
  orderId: string,
}